[package]
name = "rsbrainfuck"
version = "0.1.0"
authors = ["JayCeM <johann.carl@online.de>"]
edition = "2018"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#char_stream = "0.1.8"
structopt = "0.3.21"
